# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: thda-sil <thda-sil@student.42.rio>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/08 04:46:35 by thda-sil          #+#    #+#              #
#    Updated: 2024/06/08 05:42:10 by thda-sil         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = philo

SRC = 

OBJ = $(SRC:.c=.o)

COMPILER = cc

FLAGS = -Wall -Wextra -Werror

.c.o: 

$(NAME):

all: $(NAME)

clean:

fclean:

re:

.PHONY: all clean fclean re 
